Project 1 - Kirill Zolotuskiy
Kirill-iceland/Python-project-1_2024_Kirill-Zolotuskiy pull request #2
Opened 2024-04-08 08:56 UTC by Kirill-iceland

2024-04-11 20:52 UTC, arncpp requested changes

2024-04-11 20:52 UTC, arncpp commented on MazeCreator.py
> +sys.path.append('src/windows')
это стоит делать после импортов
и 
прямое объединение путей в виде строк `"src/windows/"`  может привести к такой проблеме:
строковый путь, который работает на одной операционной системе, может быть неправильным на другой. 
Например, Unix-системы используют `/` для разделения директорий, в то время как Windows использует `\`. Захардкоженные пути могут неправильно интерпретироваться

стоит делать так
```
os.path.join("src", "windows")
```

2024-04-11 20:52 UTC, arncpp commented on MazeCreator.py
> +from Generate import Generate
импорты делятся на несколько блоков, которые нужно разделять:
1) Стандартные библиотеки Python:
Сюда входят все встроенные модули и пакеты, такие как os, sys, datetime, logging и т.д.
2) Сторонние библиотеки (third-party):
Импорты из библиотек, установленных через менеджеры пакетов, например, pip. Это могут быть библиотеки, такие как numpy, pandas, requests и т.д.
3) Локальные импорты (модули текущего приложения или проекта):
Импорты из модулей, написанных в рамках текущего проекта.

Порядок импортов выглядит соответственно так:
```import os
import sys

import numpy as np
import pandas as pd

import a_my_module
import b_my_module
from a_my_module import MyClass```
Импорты в блоках должны быть в алфавитном порядке.

2024-04-11 20:52 UTC, arncpp commented on MazeCreator.py
> +pygame.quit()
стоит это вынести в какой-то класс или метод и запускать так
```
if __name__ == '__main__':
    start()
```

2024-04-11 20:52 UTC, arncpp commented on src/algorithms/AStar.py
> +        for i in range(maze.height):
блоки кода с for, while, if и тд стоит отделять пустыми строками для лучше читаемости

2024-04-21 14:41 UTC, arncpp requested changes
последние правки и засчитываю)

2024-04-21 14:41 UTC, arncpp commented on MazeCreator.py
> +import os
неиспользуемые импорты

2024-04-21 14:41 UTC, arncpp commented on MazeCreator.py
> +        icon = pygame.image.load('src/img/icon.png')
прямое объединение путей в виде строк `"src/img/icon.png"`  может привести к такой проблеме:
строковый путь, который работает на одной операционной системе, может быть неправильным на другой. 
Например, Unix-системы используют `/` для разделения директорий, в то время как Windows использует `\`. Захардкоженные пути могут неправильно интерпретироваться

стоит делать так
```
os.path.join("src", "img", "icon.png")
```

2024-04-21 14:41 UTC, arncpp commented on MazeCreator.py
файлы принято именовать camel_case'ом, то есть `maze_creator.py`

2024-04-24 08:53 UTC, Kirill-iceland commented on MazeCreator.py
camelCase это другое `maze_creator.py` это snake_case

2024-04-29 00:13 UTC, arncpp approved these changes

2024-04-29 01:25 UTC, arncpp commented on MazeCreator.py
ахахах да, сорри
сонная была и попутала)

2024-05-01 13:39 UTC, merged